;;*****************************************************************************
;;*****************************************************************************
;;  FILENAME: DELSIG11_1INT.asm
;;   Version: 1.50, Updated on 2014/7/14 at 8:11:19
;;  Generated by PSoC Designer 5.4.2946
;;
;;  DESCRIPTION: Assembler interrupt service routine for the Delta-Sigma ADC
;;               User Module based on the Type 2 Decimator. This code works for
;;               both the first and second-order modulator topologies where
;;               the decimation rate requires no extra software shifts.
;;-----------------------------------------------------------------------------
;;  Copyright (c) Cypress Semiconductor 2014. All Rights Reserved.
;;*****************************************************************************
;;*****************************************************************************

include "m8c.inc"
include "memory.inc"
include "DELSIG11_1.inc"


;-----------------------------------------------
;  Global Symbols
;-----------------------------------------------

export _DELSIG11_1_ADConversion_ISR
export _DELSIG11_1_cResult
export  DELSIG11_1_cResult
export _DELSIG11_1_bfStatus
export  DELSIG11_1_bfStatus


;-----------------------------------------------
; Variable Allocation
;-----------------------------------------------
AREA InterruptRAM (RAM, REL, CON)

_DELSIG11_1_cResult:
 DELSIG11_1_cResult:               blk 1             ;ADC output value
_DELSIG11_1_bfStatus:
 DELSIG11_1_bfStatus:              blk 1             ;Data Valid Flag


;-----------------------------------------------
;  Private Symbols
;-----------------------------------------------
MSB:                               equ 0
LSB:                               equ 1
RES:                               equ 8
UMAX:                              equ (1<<RES) - 1  ; 2^RES - 1


;@PSoC_UserCode_INIT@ (Do not change this line.)
;---------------------------------------------------
; Insert your custom declarations below this banner
;---------------------------------------------------

;------------------------
; Includes
;------------------------

;------------------------
; Exports
;------------------------

;------------------------
; Constant Definitions
;------------------------

;------------------------
; Variable Allocation
;------------------------

;---------------------------------------------------
; Insert your custom declarations above this banner
;---------------------------------------------------
;@PSoC_UserCode_END@ (Do not change this line.)


AREA UserModules (ROM, REL, CON)

;;=============================================================================
;;  FUNCTION NAME: _DELSIG11_1_ADConversion_ISR:
;;=============================================================================
;;
_DELSIG11_1_ADConversion_ISR:
   push  A
   mov   A, reg[DEC_DH]                    ; Is value >= 2^RES?
   jz    .NormalRange                      ;    No, normal range
   mov   A, reg[DEC_DL]
   mov   A, UMAX                           ;   Yes, limit to 2^RES - 1
   jmp   .ConversionReady
.NormalRange:
   mov   A, reg[DEC_DL]

.ConversionReady:
IF DELSIG11_1_2S_COMPLEMENT
   ; Internal hardware format is unsigned; convert so zero is half scale
   sub   A, (UMAX+1)>>1
ENDIF
   mov [DELSIG11_1_cResult],  A
   mov [DELSIG11_1_bfStatus], DELSIG11_1_DATA_READY_BIT        ; Set valid data flag


   ;@PSoC_UserCode_BODY@ (Do not change this line.)
   ;---------------------------------------------------
   ; Insert your custom code below this banner
   ;---------------------------------------------------


   ;---------------------------------------------------
   ; Insert your custom code above this banner
   ;---------------------------------------------------
   ;@PSoC_UserCode_END@ (Do not change this line.)
   pop   A
   reti

; end of file DELSIG11_1INT.asm
